id: ingester
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: ingester
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: ingester
        containers:
          - name: ingester
            image: 172.17.8.101:5001/ingester
            #command:
            #  - /run.sh
            cpu: 1000
            ports:
              - name: cql
                containerPort: 9042
              - name: thrift
                containerPort: 9160
            #volumeMounts:
            #  - name: data
            #    mountPath: /ingester_data
            env:
              - key: MAX_HEAP_SIZE
                value: 512M
              - key: HEAP_NEWSIZE
                value: 100M
        volumes:
          - name: data
            source:
              emptyDir: {}
    labels:
      name: ingester
